### ISSUE TITLE
Template error in Redmine 1.2.2

### ISSUE THREAD

**Issue by AntonioIEF** [alvila/redmine_reminder#11]
In Redmine 1.2.0 everything works good.
Rails=2.3.11

But when i update to 1.2.2 (rails =2.3.14) i got an error

"Missing template reminder_all/reminder_all.text.erb in view path vendor/plugins/redmine_issue_notification/app/views:vendor/plugins/redmine_reminder/app/views:app/viewsvendor/plugins/redmine_issue_notification/app/views:vendor/plugins/redmine_reminder/app/views:app/views"

**Comment by AntonioIEF** [comment]
Sorry.
I try to update by another method and everything works... Thank you for so great plugin )))

**Comment by mrMoe** [comment]
Hello,

can you please provide your solution for the error because I have the same with redmine 1.3.0

thanks

**Comment by avances123** [comment]
I see here:
http://www.redmine.org/boards/2/topics/28462

the api-call seems to have changed from

rake redmine:send_reminders_all RAILS_ENV=production

to

rake redmine:send_reminders RAILS_ENV=production

But no email recieved... Now debuging my email server.

**Comment by AntonioIEF** [comment]
I dont remember exactly )))
i rename files in ...ine/vendor/plugins/redmine_reminder/app/views/reminder_all
reminder_all.text.html.rhtml
reminder_all.text.plain.rhtml
to 
reminder_all.html.erb
reminder_all.text.plain.erb

and i have one more file reminder_all.text.erb it is the same as reminder_all.text.html.rhtml
